[package]
name = "rustpeuler"
version = "0.1.0"
authors = ["yellowtides <andi.dicu12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "plist"
path = "src/sol/lib.rs"

[dependencies]
num-bigint = "0.3"